### PR TITLE
Integration of Sklar's code... builds and runs... 

### PR DESCRIPTION
**Pull request by dfsklar**
... but Sklar's custom views not yet instantiated in the UX.

Note change the Podfile -- you must do a pod install !

### CODE REVIEW

**Comment by mysterycommand** [comment]
Must I `pod install`? Aren't the Pods all checked in? I see some `kxMenu` stuff in the files changed … hmm, looks like you're right … do you want to just add the Pods? After `pod install` it runs, but:

```
$ git status
On branch sklard-integrate
Your branch is up-to-date with 'origin/sklard-integrate'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   Pods/Pods.xcodeproj/project.pbxproj

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    Pods/Headers/Private/YLLongTapShare/
    Pods/Pods.xcodeproj/xcuserdata/mhayes.xcuserdatad/
    Pods/Target Support Files/YLLongTapShare/
    Pods/YLLongTapShare/
    soundwich.xcodeproj/xcuserdata/mhayes.xcuserdatad/
    soundwich.xcworkspace/xcuserdata/mhayes.xcuserdatad/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by dfsklar** [comment]
I don't think all the pods are committed.  Do indeed try a pod install if you can't get things to work.  Note that the kxMenu stuff is not pod-related - that is a package that I brought in via code instead of via pod.

Note: this PR has just been changed to incorporate instantiation of the timeline widget - it now dominates the editor VC but leaves room at the bottom for a record button.

**Comment by dfsklar** [comment]
@mysterycommand   - please see latest commit, now the timeline view is auto-instantiated into the editor VC.  It is blank (no soundbites) but it's ready to start receiving content.

**Comment by dfsklar** [comment]
OK I see now that the protocol has been to go ahead and commit into the repo everything under Pods/ -- I had not added the new pod files/dirs to the repo.   I'm going to make another commit to correct that.

**Comment by dfsklar** [comment]
@mysterycommand  the entire pod tree is now available on the HEAD of this branch.

**Comment by mysterycommand** [comment]
:+1: LGTM … builds and runs. Please see my [PR 12](https://github.com/soundwiches/soundwich-ios/pull/12) to add a `.gitignore` so that the `*xcuserdata` stuff gets ignored when we're each working on this project.

**Pull request merged**
